--
-- PostgreSQL database dump
--

\restrict 5qRkyb5K1ozz702Axqz0iANFtnFcBv52VKd1sbvZq7qZVL75w0abKndRecPT888

-- Dumped from database version 18.6
-- Dumped by pg_dump version 18.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: book_copies; Type: TABLE; Schema: public; Owner: smartlibrary_user
--

CREATE TABLE public.book_copies (
    id bigint NOT NULL,
    copy_code character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    book_id bigint NOT NULL
);


ALTER TABLE public.book_copies OWNER TO smartlibrary_user;

--
-- Name: book_copies_id_seq; Type: SEQUENCE; Schema: public; Owner: smartlibrary_user
--

ALTER TABLE public.book_copies ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.book_copies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: books; Type: TABLE; Schema: public; Owner: smartlibrary_user
--

CREATE TABLE public.books (
    id bigint NOT NULL,
    author character varying(255) NOT NULL,
    available_copies integer,
    category character varying(255),
    description character varying(2000),
    isbn character varying(255) NOT NULL,
    title character varying(255) NOT NULL,
    total_copies integer,
    cover_image_url character varying(1000)
);


ALTER TABLE public.books OWNER TO smartlibrary_user;

--
-- Name: books_id_seq; Type: SEQUENCE; Schema: public; Owner: smartlibrary_user
--

ALTER TABLE public.books ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.books_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: chat_messages; Type: TABLE; Schema: public; Owner: smartlibrary_user
--

CREATE TABLE public.chat_messages (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    message text NOT NULL,
    read_status boolean NOT NULL,
    receiver_id bigint NOT NULL,
    sender_id bigint NOT NULL
);


ALTER TABLE public.chat_messages OWNER TO smartlibrary_user;

--
-- Name: chat_messages_id_seq; Type: SEQUENCE; Schema: public; Owner: smartlibrary_user
--

ALTER TABLE public.chat_messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: circulation; Type: TABLE; Schema: public; Owner: smartlibrary_user
--

CREATE TABLE public.circulation (
    id bigint NOT NULL,
    due_date date NOT NULL,
    issue_date date NOT NULL,
    return_date date,
    status character varying(255) NOT NULL,
    book_copy_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.circulation OWNER TO smartlibrary_user;

--
-- Name: circulation_id_seq; Type: SEQUENCE; Schema: public; Owner: smartlibrary_user
--

ALTER TABLE public.circulation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.circulation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reminders; Type: TABLE; Schema: public; Owner: smartlibrary_user
--

CREATE TABLE public.reminders (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    message text NOT NULL,
    read_status boolean NOT NULL,
    title character varying(255) NOT NULL,
    type character varying(255) NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.reminders OWNER TO smartlibrary_user;

--
-- Name: reminders_id_seq; Type: SEQUENCE; Schema: public; Owner: smartlibrary_user
--

ALTER TABLE public.reminders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reminders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reservations; Type: TABLE; Schema: public; Owner: smartlibrary_user
--

CREATE TABLE public.reservations (
    id bigint NOT NULL,
    fulfilled_date timestamp(6) without time zone,
    queue_position integer NOT NULL,
    reservation_date timestamp(6) without time zone NOT NULL,
    status character varying(255) NOT NULL,
    book_id bigint NOT NULL,
    user_id bigint NOT NULL,
    held_copy_id bigint
);


ALTER TABLE public.reservations OWNER TO smartlibrary_user;

--
-- Name: reservations_id_seq; Type: SEQUENCE; Schema: public; Owner: smartlibrary_user
--

ALTER TABLE public.reservations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reservations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: smartlibrary_user
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    role character varying(255) NOT NULL
);


ALTER TABLE public.users OWNER TO smartlibrary_user;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: smartlibrary_user
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: book_copies; Type: TABLE DATA; Schema: public; Owner: smartlibrary_user
--

COPY public.book_copies (id, copy_code, status, book_id) FROM stdin;
1	CLEAN-001	HELD	1
7	EJ-002	AVAILABLE	2
9	JCR-002	AVAILABLE	3
10	JCR-003	AVAILABLE	3
11	PCC-001	AVAILABLE	4
12	PCC-002	AVAILABLE	4
13	PCC-003	AVAILABLE	4
15	DSC-002	AVAILABLE	5
16	DDIA-001	AVAILABLE	6
17	DDIA-002	AVAILABLE	6
2	CLEAN-002	HELD	1
6	EJ-001	AVAILABLE	2
3	CLEAN-003	HELD	1
14	DSC-001	AVAILABLE	5
18	9781449355739-COPY-3	AVAILABLE	6
19	9780134685991-COPY-3	AVAILABLE	2
21	9781449355739-COPY-4	AVAILABLE	6
22	9781449355739-COPY-5	AVAILABLE	6
20	9780132350884-COPY-4	ISSUED	1
8	JCR-001	AVAILABLE	3
\.


--
-- Data for Name: books; Type: TABLE DATA; Schema: public; Owner: smartlibrary_user
--

COPY public.books (id, author, available_copies, category, description, isbn, title, total_copies, cover_image_url) FROM stdin;
5	Abraham Silberschatz	2	Database	A comprehensive introduction to database systems, SQL and database design.	9780078022159	Database System Concepts	2	https://covers.openlibrary.org/b/isbn/9780078022159-L.jpg
6	Martin Kleppmann	5	Database	Concepts and practical approaches for building reliable and scalable data systems.	9781449355739	Designing Data-Intensive Applications	5	https://covers.openlibrary.org/b/isbn/9781449373320-L.jpg
1	Robert C. Martin	0	Programming	A practical book about writing clean, readable and maintainable software.	9780132350884	Clean Code	4	https://covers.openlibrary.org/b/isbn/9780132350884-L.jpg
3	Herbert Schildt	3	Java	A comprehensive guide to Java programming, APIs and object-oriented development.	9780135166307	Java: The Complete Reference	3	https://covers.openlibrary.org/b/isbn/9781260440232-L.jpg
2	Joshua Bloch	3	Java	Best practices and design patterns for writing robust Java applications.	9780134685991	Effective Java	3	https://covers.openlibrary.org/b/isbn/9780134685991-L.jpg
4	Eric Matthes	3	Python	A practical introduction to Python programming and application development.	9781718502703	Python Crash Course	3	https://covers.openlibrary.org/b/isbn/9781593279288-L.jpg
\.


--
-- Data for Name: chat_messages; Type: TABLE DATA; Schema: public; Owner: smartlibrary_user
--

COPY public.chat_messages (id, created_at, message, read_status, receiver_id, sender_id) FROM stdin;
1	2026-10-03 11:44:36.515279	i cant find book	f	4	5
2	2026-10-03 11:52:55.352694	which book you want?	f	5	4
3	2026-10-03 12:21:30.855887	Hello, I need help finding a book.	f	4	5
4	2026-10-03 12:21:55.458125	which book ?	f	5	4
\.


--
-- Data for Name: circulation; Type: TABLE DATA; Schema: public; Owner: smartlibrary_user
--

COPY public.circulation (id, due_date, issue_date, return_date, status, book_copy_id, user_id) FROM stdin;
1	2026-10-08	2026-10-01	2026-10-01	RETURNED	1	1
2	2026-10-08	2026-10-01	2026-10-02	RETURNED	1	1
5	2026-10-09	2026-10-02	2026-10-02	RETURNED	1	1
6	2026-10-09	2026-10-02	2026-10-02	RETURNED	1	2
3	2026-10-08	2026-10-01	2026-10-03	RETURNED	2	1
7	2026-10-28	2026-10-03	2026-10-03	RETURNED	6	5
4	2026-10-08	2026-10-01	2026-10-03	RETURNED	3	1
8	2026-10-10	2026-10-03	2026-10-03	RETURNED	14	5
10	2026-10-14	2026-10-07	\N	ISSUED	20	5
9	2026-10-13	2026-10-06	2026-10-07	RETURNED	8	5
\.


--
-- Data for Name: reminders; Type: TABLE DATA; Schema: public; Owner: smartlibrary_user
--

COPY public.reminders (id, created_at, message, read_status, title, type, user_id) FROM stdin;
2	2026-10-03 11:24:11.003895	your book is due	t	submit your book	LIBRARIAN	5
1	2026-10-03 11:17:41.242556	submit your book	t	Library Reminder	LIBRARIAN	5
\.


--
-- Data for Name: reservations; Type: TABLE DATA; Schema: public; Owner: smartlibrary_user
--

COPY public.reservations (id, fulfilled_date, queue_position, reservation_date, status, book_id, user_id, held_copy_id) FROM stdin;
1	2026-10-02 01:12:03.268015	1	2026-10-02 00:57:11.254361	READY	1	1	\N
2	2026-10-02 23:12:41.222878	2	2026-10-02 01:00:03.373121	READY	1	2	1
3	2026-10-03 01:16:28.718126	3	2026-10-02 23:28:56.064366	READY	1	3	2
5	\N	5	2026-10-03 01:17:07.495602	WAITING	1	4	\N
4	2026-10-03 01:23:34.531888	4	2026-10-03 00:49:53.393011	READY	1	5	3
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: smartlibrary_user
--

COPY public.users (id, email, name, password, role) FROM stdin;
1	janhvi@example.com	Janhvi Mishra	demo123	STUDENT
2	krrish@example.com	Krrish Malvi	krrish123	STUDENT
3	teststudent@example.com	Test Student	$2a$10$Y1u1aGIjY6KocUwBs5XHV.Vp8bN9VPcID8hc7H9jQz1XtybYHpgfG	STUDENT
4	librarian@example.com	Library Admin	$2a$10$63Xeo94wIkpMdd6Q60FMFu5w.pv2CeofJEtZ3uVQXezdlme.tQHFu	LIBRARIAN
5	Aaditi@example.com	Aaditi	$2a$10$rz80jnqgE24GegEocHdfxeNDBT5Kz5CN/FHyQ.oD5Inin7mx7qV/2	STUDENT
6	krrishmalvi@example.com	krrish Malvi	$2a$10$wBNyi0VJHQ2oDyVBfJhsDuhvASKjpVD9fk5voOorGfHG7lQXd2ZKe	STUDENT
7	janvi@example.com	Janvi Padia	$2a$10$mr5ai6pLiz6CpcEmVTCU2OHpr7Z5r36HxO1wKT95tqaUuSOFO6joq	STUDENT
8	neha@example.com	neha 	$2a$10$z5HQ0LxvXnSuG2L1kXBr4eN6z5zqzSYtsNpcmWMW0ojZzhyAhEpGG	STUDENT
\.


--
-- Name: book_copies_id_seq; Type: SEQUENCE SET; Schema: public; Owner: smartlibrary_user
--

SELECT pg_catalog.setval('public.book_copies_id_seq', 22, true);


--
-- Name: books_id_seq; Type: SEQUENCE SET; Schema: public; Owner: smartlibrary_user
--

SELECT pg_catalog.setval('public.books_id_seq', 6, true);


--
-- Name: chat_messages_id_seq; Type: SEQUENCE SET; Schema: public; Owner: smartlibrary_user
--

SELECT pg_catalog.setval('public.chat_messages_id_seq', 4, true);


--
-- Name: circulation_id_seq; Type: SEQUENCE SET; Schema: public; Owner: smartlibrary_user
--

SELECT pg_catalog.setval('public.circulation_id_seq', 10, true);


--
-- Name: reminders_id_seq; Type: SEQUENCE SET; Schema: public; Owner: smartlibrary_user
--

SELECT pg_catalog.setval('public.reminders_id_seq', 2, true);


--
-- Name: reservations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: smartlibrary_user
--

SELECT pg_catalog.setval('public.reservations_id_seq', 5, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: smartlibrary_user
--

SELECT pg_catalog.setval('public.users_id_seq', 8, true);


--
-- Name: book_copies book_copies_pkey; Type: CONSTRAINT; Schema: public; Owner: smartlibrary_user
--

ALTER TABLE ONLY public.book_copies
    ADD CONSTRAINT book_copies_pkey PRIMARY KEY (id);


--
-- Name: books books_pkey; Type: CONSTRAINT; Schema: public; Owner: smartlibrary_user
--

ALTER TABLE ONLY public.books
    ADD CONSTRAINT books_pkey PRIMARY KEY (id);


--
-- Name: chat_messages chat_messages_pkey; Type: CONSTRAINT; Schema: public; Owner: smartlibrary_user
--

ALTER TABLE ONLY public.chat_messages
    ADD CONSTRAINT chat_messages_pkey PRIMARY KEY (id);


--
-- Name: circulation circulation_pkey; Type: CONSTRAINT; Schema: public; Owner: smartlibrary_user
--

ALTER TABLE ONLY public.circulation
    ADD CONSTRAINT circulation_pkey PRIMARY KEY (id);


--
-- Name: reminders reminders_pkey; Type: CONSTRAINT; Schema: public; Owner: smartlibrary_user
--

ALTER TABLE ONLY public.reminders
    ADD CONSTRAINT reminders_pkey PRIMARY KEY (id);


--
-- Name: reservations reservations_pkey; Type: CONSTRAINT; Schema: public; Owner: smartlibrary_user
--

ALTER TABLE ONLY public.reservations
    ADD CONSTRAINT reservations_pkey PRIMARY KEY (id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: smartlibrary_user
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: book_copies ukf2bi6ld4nn88uyra2kgxn6py2; Type: CONSTRAINT; Schema: public; Owner: smartlibrary_user
--

ALTER TABLE ONLY public.book_copies
    ADD CONSTRAINT ukf2bi6ld4nn88uyra2kgxn6py2 UNIQUE (copy_code);


--
-- Name: books ukkibbepcitr0a3cpk3rfr7nihn; Type: CONSTRAINT; Schema: public; Owner: smartlibrary_user
--

ALTER TABLE ONLY public.books
    ADD CONSTRAINT ukkibbepcitr0a3cpk3rfr7nihn UNIQUE (isbn);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: smartlibrary_user
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: chat_messages fkand7mh9iu4kt3n1tn2w9i9of0; Type: FK CONSTRAINT; Schema: public; Owner: smartlibrary_user
--

ALTER TABLE ONLY public.chat_messages
    ADD CONSTRAINT fkand7mh9iu4kt3n1tn2w9i9of0 FOREIGN KEY (receiver_id) REFERENCES public.users(id);


--
-- Name: reservations fkb5g9io5h54iwl2inkno50ppln; Type: FK CONSTRAINT; Schema: public; Owner: smartlibrary_user
--

ALTER TABLE ONLY public.reservations
    ADD CONSTRAINT fkb5g9io5h54iwl2inkno50ppln FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: reminders fkgibc0ij0e4s7bkldn4xybaanb; Type: FK CONSTRAINT; Schema: public; Owner: smartlibrary_user
--

ALTER TABLE ONLY public.reminders
    ADD CONSTRAINT fkgibc0ij0e4s7bkldn4xybaanb FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: chat_messages fkgiqeap8ays4lf684x7m0r2729; Type: FK CONSTRAINT; Schema: public; Owner: smartlibrary_user
--

ALTER TABLE ONLY public.chat_messages
    ADD CONSTRAINT fkgiqeap8ays4lf684x7m0r2729 FOREIGN KEY (sender_id) REFERENCES public.users(id);


--
-- Name: book_copies fkhlawea8y2e2dv0ta58vc6f5nr; Type: FK CONSTRAINT; Schema: public; Owner: smartlibrary_user
--

ALTER TABLE ONLY public.book_copies
    ADD CONSTRAINT fkhlawea8y2e2dv0ta58vc6f5nr FOREIGN KEY (book_id) REFERENCES public.books(id);


--
-- Name: circulation fkj35vbymr8im5tqn0lxg37lt15; Type: FK CONSTRAINT; Schema: public; Owner: smartlibrary_user
--

ALTER TABLE ONLY public.circulation
    ADD CONSTRAINT fkj35vbymr8im5tqn0lxg37lt15 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: circulation fkjrj2585jd5nmkk88fehptyjno; Type: FK CONSTRAINT; Schema: public; Owner: smartlibrary_user
--

ALTER TABLE ONLY public.circulation
    ADD CONSTRAINT fkjrj2585jd5nmkk88fehptyjno FOREIGN KEY (book_copy_id) REFERENCES public.book_copies(id);


--
-- Name: reservations fkkxi0ata95oecc2dqjurvyuabj; Type: FK CONSTRAINT; Schema: public; Owner: smartlibrary_user
--

ALTER TABLE ONLY public.reservations
    ADD CONSTRAINT fkkxi0ata95oecc2dqjurvyuabj FOREIGN KEY (held_copy_id) REFERENCES public.book_copies(id);


--
-- Name: reservations fkrsdd3ib3landfpmgoolccjakt; Type: FK CONSTRAINT; Schema: public; Owner: smartlibrary_user
--

ALTER TABLE ONLY public.reservations
    ADD CONSTRAINT fkrsdd3ib3landfpmgoolccjakt FOREIGN KEY (book_id) REFERENCES public.books(id);


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: pg_database_owner
--

GRANT ALL ON SCHEMA public TO smartlibrary_user;


--
-- PostgreSQL database dump complete
--

\unrestrict 5qRkyb5K1ozz702Axqz0iANFtnFcBv52VKd1sbvZq7qZVL75w0abKndRecPT888

